spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ams_db?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: toilamanh123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update

server:
  port: 8889

app:
  security:
    secret-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCPqVE+9VJoOK8N3